version: '3'
services:
    app:
        build:
          context: .
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
