version: '3'
services:
    app:
        build: .
        volumes:
          - ./:/var/www/html
        ports:
          - 8080:80
        links:
          - db

    db:
      image: mysql:5
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: ebiller_root_password
        MYSQL_DATABASE: ebiller_db
        MYSQL_USER: ebiller_admin
        MYSQL_PASSWORD: ebiller_password
